# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-18 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shpmc', models.CharField(max_length=50)),
                ('shpshl', models.CharField(max_length=6)),
                ('shpjg', models.CharField(max_length=6)),
            ],
        ),
    ]
